# Generated by Django 4.0.3 on 2022-03-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mark', models.CharField(max_length=100, verbose_name='Марка')),
                ('Model', models.CharField(max_length=100, verbose_name='Модель')),
                ('Year', models.IntegerField(verbose_name='Год выпуска')),
                ('Link', models.CharField(max_length=300, verbose_name='Ссылка')),
                ('EngineCapacity', models.FloatField(verbose_name='Объем двигателя')),
                ('EnginePower', models.IntegerField(verbose_name='Мощность двигателя')),
                ('FuelType', models.CharField(max_length=50, verbose_name='Вид топлива')),
                ('Transmission', models.CharField(max_length=50, verbose_name='Тип трансмисси')),
                ('DriveWheels', models.CharField(max_length=50, verbose_name='Тип привода')),
                ('Mileage', models.IntegerField(verbose_name='Пробег')),
                ('Price', models.IntegerField(verbose_name='Цена')),
                ('Image', models.CharField(max_length=300, verbose_name='Картинка')),
                ('Location', models.CharField(max_length=100, verbose_name='Местоположение')),
            ],
        ),
    ]
