# Generated by Django 4.0.3 on 2022-04-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('mark', models.TextField(db_column='Mark')),
                ('model', models.TextField(db_column='Model')),
                ('year', models.IntegerField(db_column='Year')),
                ('link', models.TextField(db_column='Link')),
                ('enginecapacity', models.TextField(blank=True, db_column='EngineCapacity', null=True)),
                ('enginepower', models.IntegerField(blank=True, db_column='EnginePower', null=True)),
                ('fueltype', models.TextField(blank=True, db_column='FuelType', null=True)),
                ('transmission', models.TextField(blank=True, db_column='Transmission', null=True)),
                ('drivewheels', models.TextField(blank=True, db_column='DriveWheels', null=True)),
                ('milage', models.IntegerField(blank=True, db_column='Milage', null=True)),
                ('price', models.IntegerField(blank=True, db_column='Price', null=True)),
                ('image', models.TextField(blank=True, db_column='Image', null=True)),
                ('location', models.TextField(blank=True, db_column='Location', null=True)),
            ],
            options={
                'db_table': 'Auto',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
