# Generated by Django 4.0.3 on 2022-04-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_adsbookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsbookmark',
            name='ad',
            field=models.IntegerField(db_column='ad_id'),
        ),
        migrations.AlterField(
            model_name='adsbookmark',
            name='user',
            field=models.IntegerField(db_column='user_id'),
        ),
    ]
